### PR TITLE
fix: external repositories link crash

### LINKED ISSUE #15: Fetch Comments Crash
Looks like the comment incentives fail to fetch comments sometimes. Use this scenario for debugging and fix the root issue. 

> ```diff
> + Evaluating results. Please wait...
> ```

> I can manually pay out for the assignee (200 USD) https://gnosisscan.io/tx/0x090ed3c34a0cbecbf5cb87d2aa69fffb484551fed1db8f94ff6517f7ee255703

> @FernandVEYRIER if you want the comment incentives as well, we will need to fix where it crashed first. 

> https://github.com/ubiquibot/comment-incentives/actions/runs/7881915632/job/21506313614#step:5:75

> https://github.com/ubiquibot/comment-incentives/blob/626aed050d2040e389608851de73481abb3fd017/src/index.ts#L166

_Originally posted by @pavlovcik in https://github.com/ubiquity/devpool-directory-bounties/issues/14#issuecomment-1940770424_

### PR DESCRIPTION
**Pull request by FernandVEYRIER**
Resolves #15

### CODE REVIEW

**Comment by pavlovcik** [comment]
Do you have a link to a good GitHub Actions run?

**Review by pavlovcik — CHANGES_REQUESTED** [review]
It doesn't look like any functional changes. Just debugging related.

**Comment by FernandVEYRIER** [comment]
> It doesn't look like any functional changes. Just debugging related.

The issue was that the check for remote repositories was done with the wrong variables here
```TypeScript
    const organization = parts[parts.length - 4];
    const repository = parts[parts.length - 3];
    const currentOrganization = parts[parts.length - 4];
    const currentRepository = parts[parts.length - 3];
    const number = Number(parts[parts.length - 1]);
    const href = `https://github.com${relativeHref}`;

    if (`${organization}/${repository}` !== `${owner}/${repository}`) {
    if (`${currentOrganization}/${currentRepository}` !== `${owner}/${repository}`) {
```
it was shadowing the `repository` variable, so the test was true event if in the case of the crash we had `ubiquity/devpool-directory-bounties` against `ubiquity/devpool-directory`.

The way I tested it is locally, through a personal GitHub token, it works fine without needing to put it in GitHub action. You can test with the payload that was fed into the Action that crashed:
```TypeScript
{
  inputs: {
    collaborators: '["pavlovcik","sergfeldman","molecula451","0xCapitalist","gitcoindev","Draeieg","wannacfuture","rndquu","diamondnegroni","whilefoo","0x4007"]',
    eventName: 'issues.closed',
    installationId: '35097154',
    issueNumber: '14',
    issueOwner: 'ubiquity',
    issueRepository: 'devpool-directory-bounties'
  }
}
```

I added the output of the error in the log for convenience, because it would give a good hint on what went wrong.

**Comment by pavlovcik** [comment]
Okay your approach makes sense. I can try merging and re-running the action with the same input to verify that this indeed works.

**Review by pavlovcik — APPROVED** [review]

**Comment by pavlovcik** [comment]
I see now. On GitHub mobile it doesn't show the full file. I had to manually load the beginning lines to see that the parameters are indeed being shadowed. Nice debugging!

**Pull request merged**
