### PR TITLE
chore: add new shared evmPrivateKeyEncrypted

### PR DESCRIPTION
**Pull request by gitcoindev**
The new evmPrivateKeyEncrypted generated for address 0x3a2E44e10AbEf5CB4a6E492c5ba93d30068d2D95 (no funds).

Resolves: https://github.com/ubiquibot/comment-incentives/issues/22

### CODE REVIEW

**Comment by pavlovcik** [comment]
Need to document a private key too

**Comment by molecula451** [comment]
indeed

**Comment by gitcoindev** [comment]
@pavlovcik @molecula451 please check now again, I added to docs.

**Comment by molecula451** [comment]
go to go pavlovick, we'll be using this one for test only or test in production (lmao) ?

**Comment by gitcoindev** [comment]
No way, full details are available in plain sight, only for test purposes

**Comment by pavlovcik** [comment]
I was editing this right now but was too slow to push.

**Pull request merged**
