### PR TITLE
Rate limit workaround ts retry

### PR DESCRIPTION
**Pull request by gitcoindev**
Resolves: https://github.com/ubiquibot/permit-generation/issues/12

### CODE REVIEW

**Review by molecula451 — APPROVED** [review]
Approving looks good

**Comment by molecula451** [comment]
you reviewing here @gentlementlegen ?

**Comment by gentlementlegen** [comment]
I am fine with the code itself, but would love some associated tests with it because it is actually not easy to setup to see if it works properly.

**Comment by molecula451** [comment]
i think you can handle it @gitcoindev ?

**Pull request merged**
